# **Machine Learning Caso: Monopoly**

| Variable | Transformación | Valor | Descripcion |
|----------|----------------|-------|-------------|
| CORRELATIVO | Ninguna | 518050 | Identificador cliente |
| Region | Ninguna | 13 | Region de Residencia |
| Renta | Ninguna | NULL | Renta del cliente |
| Sexo | Ninguna | M | Sexo |
| Subsegmento | Ninguna | 151 | Subsegmento |
| Edad | Ninguna | 39 | Edad |
| Adicional | Ninguna | 0 | Indicador de Tenecia de TC adicionales |
| Antiguedad | Ninguna | 78 | Antigüedad del cliente (meses) |
| CambioPin | Ninguna | NULL | Indicador del cambio de clave secreta de la tarjeta |
| Consumo | Ninguna | 0 | Indicador de Credito de Consumo |
| Debito | Ninguna | 1 | Indicador de Tenecia de TD |
| Ctacte | Ninguna | 1 | Indicador de Cuenta Corriente |
| Cuentas | Ninguna | 1 | Numero de cuentas que tiene el cliente |
| Hipotecario | Ninguna | 0 | Indicador de Credito Hipotecario |
| Internauta | Ninguna | 1 | Indicador de cliente Internauta que usa la web Monopoly |
| Monoproducto | Ninguna | 0 | Indicador de si el cliente es solo poseedor de una TC |
| TC | Ninguna | 1 | Numero de TC que tiene el cliente |
| Dualidad | Ninguna | 0 | Indicador de Dualidad (Cliente es dual si tiene 2 o mas TC) |
| CUPO_L1 | Ninguna | 1800000 | Cupo de la tarjeta credito para compras nacionales |
| CUPO_MX | Ninguna | 3750 | Cupo de la tarjeta credito para compras internacionales |
| CUPO_L2 | Ninguna | 1 | Cupo de la tarjeta credito para avances en cuotas |
| Col_T12 | promedio | 0 | Colocacion del cliente en TC en el mes X |
| ColL1TE_T12 | | 0 | Revolving del cliente en TC en el mes X |
| EeccInt_T12 | promedio | 0 | Monto internacional exigido en el estado de cuenta del cliente en el mes X |
| EeccNac_T12 | promedio | -12178 | Monto nacional exigido en el estado de cuenta del cliente en el mes X |
| Fac_T12 | Promedio | 0 | Monto facturado por el cliente en TC en el mes X |
| FacAI_T12 | Promedio | 0 | Monto facturado en avances internacionales por el cliente en TC en el mes X |
| FacAN_T12 | Promedio | 0 | Monto facturado en avances nacionales por el cliente en TC en el mes X |
| FacCCOT_T12 | Promedio | 0 | Monto facturado en compras en cuotas con tasa por el cliente en TC en el mes X |
| FacCCPC_T12 | Promedio | 0 | Monto facturado en compras en cuotas precio contado por el cliente en TC en el mes X |
| FacCI_T12 | Promedio | 0 | Monto facturado en compras internacionales por el cliente en TC en el mes X |
| FacCN_T12 | Promedio | 0 | Monto facturado en compras nacionales por el cliente en TC en el mes X |
| FacCOL_T12 | Promedio | 0 | Monto facturado en avances en cuotas por el cliente en TC en el mes X |
| FacDebAtm_T12 | Promedio | 800000 | Monto facturado en avances por el cliente en TD en el mes X |
| FacDebCom_T12 | Promedio | 221730 | Monto facturado en compras por el cliente en TD en el mes X |
| FacPAT_T12 | Promedio | 0 | Monto facturado en PAT por el cliente en TC en el mes X |
| FlgAct_T12 | Suma meses activos | 0 | Indicador de actividad en el mes X en la TC |
| FlgActAI_T12 | Suma meses activos | 0 | Indicador de actividad en avances internacionales en el mes X en la TC |
| FlgActAN_T12 | Suma meses activos | 0 | Indicador de actividad en avances nacionales en el mes X en la TC |
| FlgActCCOT_T12 | Suma meses activos | 0 | Indicador de actividad en compras nacionales en cuotas con tasa en el mes X en la TC |
| FlgActCCPC_T12 | Suma meses activos | 0 | Indicador de actividad en compras nacionales en cuotas precio contado en el mes X en la TC |
| FlgActCI_T12 | Suma meses activos | 0 | Indicador de actividad en compras internacionales en el mes X en la TC |
| FlgActCN_T12 | Suma meses activos | 0 | Indicador de actividad en compras nacionales en el mes X en la TC |
| FlgActCOL_T12 | Suma meses activos | 0 | Indicador de actividad en avances en cuotas con tasa en el mes X en la TC |
| FlgActPAT_T12 | Suma meses activos | 0 | Indicador de actividad en PAT en el mes X en la TC |
| PagoInt_T12 | promedio | 0 | Monto de pagos de deuda internacional del cliente en el mes X |
| PagoNac_T12 | promedio | 25000 | Monto de pagos de deuda nacional del cliente en el mes X |
| Txs_T12 | Suma | 0 | Numero de transacciones realizados por el cliente en TC en el mes X |
| TxsAI_T12 | Suma | 0 | Numero de transacciones en avances internacionales realizados por el cliente en TC en el mes X |
| TxsAN_T12 | Suma | 0 | Numero de transacciones en avances nacionales realizados por el cliente en TC en el mes X |
| TxsCCOT_T12 | Suma | 0 | Numero de transacciones en compras en cuotas con tasa realizados por el cliente en TC en el mes X |
| TxsCCPC_T12 | Suma | 0 | Numero de transacciones en compras en cuotas precio contado realizados por el cliente en TC en el mes X |
| TxsCI_T12 | Suma | 0 | Numero de transacciones en compras internacionales realizados por el cliente en TC en el mes X |
| TxsCN_T12 | Suma | 0 | Numero de transacciones en compras nacionales realizados por el cliente en TC en el mes X |
| TxsCOL_T12 | Suma | 0 | Numero de transacciones en avances en cuotas por el cliente en TC en el mes X |
| TxsDebAtm_T12 | Suma | 5 | Numero de transacciones en avances realizados por el cliente en TD en el mes X |
| TxsDebCom_T12 | Suma | 9 | Numero de transacciones en compras realizados por el cliente en TD en el mes X |
| TxsPAT_T12 | Suma | 0 | Numero de transacciones en PAT realizados por el cliente en TC en el mes X |
| UsoL1_T12 | Promedio | -12178 | Monto de deuda en la linea de compras en la TC en el mes X |
| UsoL2_T12 | Promedio | 0 | Monto de deuda en la linea de avances en cuotas en la TC en el mes X |
| UsoLI_T12 | Promedio | 0 | Monto de deuda en la linea de compras internacionales en la TC en el mes X |

## **Fase 1: Business Understanding**

In [25]:
import pandas as pd

# Cargar el dataset
df = pd.read_excel('../data/Base_clientes_Monopoly-0.xlsx',sheet_name=0, header=1)

In [26]:
# Mostrar las primeras filas del dataset
df.head()

,Id,Subsegmento,Sexo,Region,Edad,Renta,Antiguedad,Internauta,Adicional,Dualidad,...,PagoNac_T01,PagoInt_T01,EeccNac_T01,EeccInt_T01,UsoL1_T01,UsoL2_T01,UsoLI_T01,IndRev_T01,target,Unnamed: 574
0,1,160,M,13.0,43,NaN,130,1,1,0,...,33000,0.0,1099866.0,0.0,1099866.0,15080,0.0,R,0,NaN
1,2,160,H,13.0,46,143640.0,69,1,0,0,...,300000,0.0,214592.0,0.0,214592.0,83596,0.0,R,0,NaN
2,3,170,H,13.0,45,929106.0,24,1,1,0,...,216676,0.0,0.0,0.0,7400.0,0,0.0,T,0,NaN
3,4,151,H,13.0,46,172447.0,134,0,1,0,...,60000,0.0,272762.0,0.0,272762.0,10591,0.0,R,0,NaN
4,5,170,H,13.0,46,805250.0,116,0,1,1,...,272925,0.0,249562.0,0.0,75339.0,377782,0.0,R,0,NaN

In [31]:
df.tail(10)

,Id,Subsegmento,Sexo,Region,Edad,Renta,Antiguedad,Internauta,Adicional,Dualidad,...,PagoNac_T01,PagoInt_T01,EeccNac_T01,EeccInt_T01,UsoL1_T01,UsoL2_T01,UsoLI_T01,IndRev_T01,target,Unnamed: 574
51114,51115,170,M,13.0,47,229938.0,79,1,1,1,...,37000,0.0,53232.0,0.0,16232.0,44946,0.0,R,0,NaN
51115,51116,170,H,3.0,50,954492.0,109,1,1,1,...,274438,0.0,228623.0,0.0,244621.0,0,0.0,T,0,NaN
51116,51117,170,H,2.0,49,NaN,66,0,1,0,...,150000,0.0,1836745.0,0.0,1836745.0,55282,0.0,R,1,NaN
51117,51118,160,M,7.0,50,731321.0,62,0,1,1,...,40000,0.0,340482.0,0.0,340482.0,17498,0.0,R,0,NaN
51118,51119,160,M,13.0,44,414316.0,23,1,0,1,...,153096,0.0,76219.0,0.0,2901.0,71455,0.0,T,0,NaN
51119,51120,160,H,13.0,51,364978.0,57,1,1,1,...,300000,0.0,478320.0,0.0,478320.0,12668,0.0,R,0,NaN
51120,51121,170,H,13.0,51,625376.0,39,1,0,0,...,166098,0.0,166098.0,0.0,0.0,572363,0.0,R,0,NaN
51121,51122,160,H,13.0,47,806220.0,153,1,1,0,...,18891,0.0,9652.0,0.0,9652.0,16241,0.0,R,0,NaN
51122,51123,160,M,13.0,47,NaN,11,1,0,0,...,26528,0.0,24638.0,0.0,24638.0,84982,0.0,R,0,NaN
51123,51124,170,H,13.0,51,840878.0,75,1,1,0,...,12360,0.0,12360.0,0.0,18500.0,0,0.0,R,0,NaN

In [39]:
columnas = df.columns
for columna in columnas:
    print(f'{columna} es de tipo {df[columna].dtype}')

Id es de tipo int64
Subsegmento es de tipo int64
Sexo es de tipo object
Region es de tipo float64
Edad es de tipo int64
Renta es de tipo float64
Antiguedad es de tipo int64
Internauta es de tipo int64
Adicional es de tipo int64
Dualidad es de tipo int64
Monoproducto es de tipo int64
Ctacte es de tipo int64
Consumo es de tipo int64
Hipotecario es de tipo int64
Debito es de tipo int64
CambioPin es de tipo float64
Cuentas es de tipo int64
TC es de tipo int64
CUPO_L1 es de tipo int64
CUPO_L2 es de tipo float64
CUPO_MX es de tipo float64
FlgAct_T12 es de tipo float64
FlgActCN_T12 es de tipo float64
FlgActCI_T12 es de tipo float64
FlgActAN_T12 es de tipo float64
FlgActAI_T12 es de tipo float64
FlgActPAT_T12 es de tipo float64
FlgActCCPC_T12 es de tipo float64
FlgActCCOT_T12 es de tipo float64
FlgActCOL_T12 es de tipo float64
Fac_T12 es de tipo float64
Txs_T12 es de tipo float64
FacCN_T12 es de tipo float64
TxsCN_T12 es de tipo float64
FacCI_T12 es de tipo float64
TxsCI_T12 es de tipo float64
FacAN_T12 es de tipo float64
TxsAN_T12 es de tipo float64
FacAI_T12 es de tipo float64
TxsAI_T12 es de tipo float64
FacPAT_T12 es de tipo float64
TxsPAT_T12 es de tipo float64
FacCCPC_T12 es de tipo float64
TxsCCPC_T12 es de tipo float64
FacCCOT_T12 es de tipo float64
TxsCCOT_T12 es de tipo float64
FacCOL_T12 es de tipo float64
TxsCOL_T12 es de tipo float64
FacDebCom_T12 es de tipo float64
TxsDebCom_T12 es de tipo float64
FacDebAtm_T12 es de tipo float64
TxsDebAtm_T12 es de tipo float64
Col_T12 es de tipo float64
ColL1T0_T12 es de tipo float64
ColL1TE_T12 es de tipo float64
ColL2T0_T12 es de tipo float64
ColL2AC_T12 es de tipo float64
ColL2CC_T12 es de tipo float64
ColMx_T12 es de tipo float64
PagoNac_T12 es de tipo float64
PagoInt_T12 es de tipo float64
EeccNac_T12 es de tipo float64
EeccInt_T12 es de tipo float64
UsoL1_T12 es de tipo float64
UsoL2_T12 es de tipo float64
UsoLI_T12 es de tipo float64
IndRev_T12 es de tipo object
FlgAct_T11 es de tipo float64
FlgActCN_T11 es de tipo float64
FlgActCI_T11 es de tipo float64
FlgActAN_T11 es de tipo float64
FlgActAI_T11 es de tipo float64
FlgActPAT_T11 es de tipo float64
FlgActCCPC_T11 es de tipo float64
FlgActCCOT_T11 es de tipo float64
FlgActCOL_T11 es de tipo float64
Fac_T11 es de tipo float64
Txs_T11 es de tipo float64
FacCN_T11 es de tipo float64
TxsCN_T11 es de tipo float64
FacCI_T11 es de tipo float64
TxsCI_T11 es de tipo float64
FacAN_T11 es de tipo float64
TxsAN_T11 es de tipo float64
FacAI_T11 es de tipo float64
TxsAI_T11 es de tipo float64
FacPAT_T11 es de tipo float64
TxsPAT_T11 es de tipo float64
FacCCPC_T11 es de tipo float64
TxsCCPC_T11 es de tipo float64
FacCCOT_T11 es de tipo float64
TxsCCOT_T11 es de tipo float64
FacCOL_T11 es de tipo float64
TxsCOL_T11 es de tipo float64
FacDebCom_T11 es de tipo float64
TxsDebCom_T11 es de tipo float64
FacDebAtm_T11 es de tipo float64
TxsDebAtm_T11 es de tipo float64
Col_T11 es de tipo float64
ColL1T0_T11 es de tipo float64
ColL1TE_T11 es de tipo float64
ColL2T0_T11 es de tipo float64
ColL2AC_T11 es de tipo float64
ColL2CC_T11 es de tipo float64
ColMx_T11 es de tipo float64
PagoNac_T11 es de tipo float64
PagoInt_T11 es de tipo float64
EeccNac_T11 es de tipo float64
EeccInt_T11 es de tipo float64
UsoL1_T11 es de tipo float64
UsoL2_T11 es de tipo float64
UsoLI_T11 es de tipo float64
IndRev_T11 es de tipo object
FlgAct_T10 es de tipo float64
FlgActCN_T10 es de tipo float64
FlgActCI_T10 es de tipo float64
FlgActAN_T10 es de tipo float64
FlgActAI_T10 es de tipo float64
FlgActPAT_T10 es de tipo float64
FlgActCCPC_T10 es de tipo float64
FlgActCCOT_T10 es de tipo float64
FlgActCOL_T10 es de tipo float64
Fac_T10 es de tipo float64
Txs_T10 es de tipo float64
FacCN_T10 es de tipo float64
TxsCN_T10 es de tipo float64
FacCI_T10 es de tipo float64
TxsCI_T10 es de tipo float64
FacAN_T10 es de tipo float64
TxsAN_T10 es de tipo float64
FacAI_T10 es de tipo float64
TxsAI_T10 es de tipo float64
FacPAT_T10 es de tipo float64
TxsPAT_T10 es de tipo float64
FacCCPC_T10 es de tipo float64
TxsCCPC_T10 es de tipo float64
FacCCOT_T10 es de tipo float64
TxsCCOT_T10 es de tipo float64
FacCOL_T10 es de tipo float64
TxsCOL_T10 es de tipo float64
FacDebCom_T10 es de tipo float64
TxsDebCom_T10 es de tipo float64
FacDebAtm_T10 es de tipo float64
TxsDebAtm_T10 es de tipo float64
Col_T10 es de tipo float64
ColL1T0_T10 es de tipo float64
ColL1TE_T10 es de tipo float64
ColL2T0_T10 es de tipo float64
ColL2AC_T10 es de tipo float64
ColL2CC_T10 es de tipo float64
ColMx_T10 es de tipo float64
PagoNac_T10 es de tipo float64
PagoInt_T10 es de tipo float64
EeccNac_T10 es de tipo float64
EeccInt_T10 es de tipo float64
UsoL1_T10 es de tipo float64
UsoL2_T10 es de tipo float64
UsoLI_T10 es de tipo float64
IndRev_T10 es de tipo object
FlgAct_T09 es de tipo float64
FlgActCN_T09 es de tipo float64
FlgActCI_T09 es de tipo float64
FlgActAN_T09 es de tipo float64
FlgActAI_T09 es de tipo float64
FlgActPAT_T09 es de tipo float64
FlgActCCPC_T09 es de tipo float64
FlgActCCOT_T09 es de tipo float64
FlgActCOL_T09 es de tipo float64
Fac_T09 es de tipo float64
Txs_T09 es de tipo float64
FacCN_T09 es de tipo float64
TxsCN_T09 es de tipo float64
FacCI_T09 es de tipo float64
TxsCI_T09 es de tipo float64
FacAN_T09 es de tipo float64
TxsAN_T09 es de tipo float64
FacAI_T09 es de tipo float64
TxsAI_T09 es de tipo float64
FacPAT_T09 es de tipo float64
TxsPAT_T09 es de tipo float64
FacCCPC_T09 es de tipo float64
TxsCCPC_T09 es de tipo float64
FacCCOT_T09 es de tipo float64
TxsCCOT_T09 es de tipo float64
FacCOL_T09 es de tipo float64
TxsCOL_T09 es de tipo float64
FacDebCom_T09 es de tipo float64
TxsDebCom_T09 es de tipo float64
FacDebAtm_T09 es de tipo float64
TxsDebAtm_T09 es de tipo float64
Col_T09 es de tipo float64
ColL1T0_T09 es de tipo float64
ColL1TE_T09 es de tipo float64
ColL2T0_T09 es de tipo float64
ColL2AC_T09 es de tipo float64
ColL2CC_T09 es de tipo float64
ColMx_T09 es de tipo float64
PagoNac_T09 es de tipo float64
PagoInt_T09 es de tipo float64
EeccNac_T09 es de tipo float64
EeccInt_T09 es de tipo float64
UsoL1_T09 es de tipo float64
UsoL2_T09 es de tipo float64
UsoLI_T09 es de tipo float64
IndRev_T09 es de tipo object
FlgAct_T08 es de tipo float64
FlgActCN_T08 es de tipo float64
FlgActCI_T08 es de tipo float64
FlgActAN_T08 es de tipo float64
FlgActAI_T08 es de tipo float64
FlgActPAT_T08 es de tipo float64
FlgActCCPC_T08 es de tipo float64
FlgActCCOT_T08 es de tipo float64
FlgActCOL_T08 es de tipo float64
Fac_T08 es de tipo float64
Txs_T08 es de tipo float64
FacCN_T08 es de tipo float64
TxsCN_T08 es de tipo float64
FacCI_T08 es de tipo float64
TxsCI_T08 es de tipo float64
FacAN_T08 es de tipo float64
TxsAN_T08 es de tipo float64
FacAI_T08 es de tipo float64
TxsAI_T08 es de tipo float64
FacPAT_T08 es de tipo float64
TxsPAT_T08 es de tipo float64
FacCCPC_T08 es de tipo float64
TxsCCPC_T08 es de tipo float64
FacCCOT_T08 es de tipo float64
TxsCCOT_T08 es de tipo float64
FacCOL_T08 es de tipo float64
TxsCOL_T08 es de tipo float64
FacDebCom_T08 es de tipo float64
TxsDebCom_T08 es de tipo float64
FacDebAtm_T08 es de tipo float64
TxsDebAtm_T08 es de tipo float64
Col_T08 es de tipo float64
ColL1T0_T08 es de tipo float64
ColL1TE_T08 es de tipo float64
ColL2T0_T08 es de tipo float64
ColL2AC_T08 es de tipo float64
ColL2CC_T08 es de tipo float64
ColMx_T08 es de tipo float64
PagoNac_T08 es de tipo float64
PagoInt_T08 es de tipo float64
EeccNac_T08 es de tipo float64
EeccInt_T08 es de tipo float64
UsoL1_T08 es de tipo float64
UsoL2_T08 es de tipo float64
UsoLI_T08 es de tipo float64
IndRev_T08 es de tipo object
FlgAct_T07 es de tipo float64
FlgActCN_T07 es de tipo float64
FlgActCI_T07 es de tipo float64
FlgActAN_T07 es de tipo float64
FlgActAI_T07 es de tipo float64
FlgActPAT_T07 es de tipo float64
FlgActCCPC_T07 es de tipo float64
FlgActCCOT_T07 es de tipo float64
FlgActCOL_T07 es de tipo float64
Fac_T07 es de tipo float64
Txs_T07 es de tipo float64
FacCN_T07 es de tipo float64
TxsCN_T07 es de tipo float64
FacCI_T07 es de tipo float64
TxsCI_T07 es de tipo float64
FacAN_T07 es de tipo float64
TxsAN_T07 es de tipo float64
FacAI_T07 es de tipo float64
TxsAI_T07 es de tipo float64
FacPAT_T07 es de tipo float64
TxsPAT_T07 es de tipo float64
FacCCPC_T07 es de tipo float64
TxsCCPC_T07 es de tipo float64
FacCCOT_T07 es de tipo float64
TxsCCOT_T07 es de tipo float64
FacCOL_T07 es de tipo float64
TxsCOL_T07 es de tipo float64
FacDebCom_T07 es de tipo float64
TxsDebCom_T07 es de tipo float64
FacDebAtm_T07 es de tipo float64
TxsDebAtm_T07 es de tipo float64
Col_T07 es de tipo float64
ColL1T0_T07 es de tipo float64
ColL1TE_T07 es de tipo float64
ColL2T0_T07 es de tipo float64
ColL2AC_T07 es de tipo float64
ColL2CC_T07 es de tipo float64
ColMx_T07 es de tipo float64
PagoNac_T07 es de tipo float64
PagoInt_T07 es de tipo float64
EeccNac_T07 es de tipo float64
EeccInt_T07 es de tipo float64
UsoL1_T07 es de tipo float64
UsoL2_T07 es de tipo float64
UsoLI_T07 es de tipo float64
IndRev_T07 es de tipo object
FlgAct_T06 es de tipo float64
FlgActCN_T06 es de tipo float64
FlgActCI_T06 es de tipo float64
FlgActAN_T06 es de tipo float64
FlgActAI_T06 es de tipo float64
FlgActPAT_T06 es de tipo float64
FlgActCCPC_T06 es de tipo float64
FlgActCCOT_T06 es de tipo float64
FlgActCOL_T06 es de tipo float64
Fac_T06 es de tipo float64
Txs_T06 es de tipo float64
FacCN_T06 es de tipo float64
TxsCN_T06 es de tipo float64
FacCI_T06 es de tipo float64
TxsCI_T06 es de tipo float64
FacAN_T06 es de tipo float64
TxsAN_T06 es de tipo float64
FacAI_T06 es de tipo float64
TxsAI_T06 es de tipo float64
FacPAT_T06 es de tipo float64
TxsPAT_T06 es de tipo float64
FacCCPC_T06 es de tipo float64
TxsCCPC_T06 es de tipo float64
FacCCOT_T06 es de tipo float64
TxsCCOT_T06 es de tipo float64
FacCOL_T06 es de tipo float64
TxsCOL_T06 es de tipo float64
FacDebCom_T06 es de tipo float64
TxsDebCom_T06 es de tipo float64
FacDebAtm_T06 es de tipo float64
TxsDebAtm_T06 es de tipo float64
Col_T06 es de tipo float64
ColL1T0_T06 es de tipo float64
ColL1TE_T06 es de tipo float64
ColL2T0_T06 es de tipo float64
ColL2AC_T06 es de tipo float64
ColL2CC_T06 es de tipo float64
ColMx_T06 es de tipo float64
PagoNac_T06 es de tipo float64
PagoInt_T06 es de tipo float64
EeccNac_T06 es de tipo float64
EeccInt_T06 es de tipo float64
UsoL1_T06 es de tipo float64
UsoL2_T06 es de tipo float64
UsoLI_T06 es de tipo float64
IndRev_T06 es de tipo object
FlgAct_T05 es de tipo float64
FlgActCN_T05 es de tipo float64
FlgActCI_T05 es de tipo float64
FlgActAN_T05 es de tipo float64
FlgActAI_T05 es de tipo float64
FlgActPAT_T05 es de tipo float64
FlgActCCPC_T05 es de tipo float64
FlgActCCOT_T05 es de tipo float64
FlgActCOL_T05 es de tipo float64
Fac_T05 es de tipo float64
Txs_T05 es de tipo float64
FacCN_T05 es de tipo float64
TxsCN_T05 es de tipo float64
FacCI_T05 es de tipo float64
TxsCI_T05 es de tipo float64
FacAN_T05 es de tipo float64
TxsAN_T05 es de tipo float64
FacAI_T05 es de tipo float64
TxsAI_T05 es de tipo float64
FacPAT_T05 es de tipo float64
TxsPAT_T05 es de tipo float64
FacCCPC_T05 es de tipo float64
TxsCCPC_T05 es de tipo float64
FacCCOT_T05 es de tipo float64
TxsCCOT_T05 es de tipo float64
FacCOL_T05 es de tipo float64
TxsCOL_T05 es de tipo float64
FacDebCom_T05 es de tipo float64
TxsDebCom_T05 es de tipo float64
FacDebAtm_T05 es de tipo float64
TxsDebAtm_T05 es de tipo float64
Col_T05 es de tipo float64
ColL1T0_T05 es de tipo float64
ColL1TE_T05 es de tipo float64
ColL2T0_T05 es de tipo float64
ColL2AC_T05 es de tipo float64
ColL2CC_T05 es de tipo float64
ColMx_T05 es de tipo float64
PagoNac_T05 es de tipo float64
PagoInt_T05 es de tipo float64
EeccNac_T05 es de tipo float64
EeccInt_T05 es de tipo float64
UsoL1_T05 es de tipo float64
UsoL2_T05 es de tipo float64
UsoLI_T05 es de tipo float64
IndRev_T05 es de tipo object
FlgAct_T04 es de tipo float64
FlgActCN_T04 es de tipo float64
FlgActCI_T04 es de tipo float64
FlgActAN_T04 es de tipo float64
FlgActAI_T04 es de tipo float64
FlgActPAT_T04 es de tipo float64
FlgActCCPC_T04 es de tipo float64
FlgActCCOT_T04 es de tipo float64
FlgActCOL_T04 es de tipo float64
Fac_T04 es de tipo float64
Txs_T04 es de tipo float64
FacCN_T04 es de tipo float64
TxsCN_T04 es de tipo float64
FacCI_T04 es de tipo float64
TxsCI_T04 es de tipo float64
FacAN_T04 es de tipo float64
TxsAN_T04 es de tipo float64
FacAI_T04 es de tipo float64
TxsAI_T04 es de tipo float64
FacPAT_T04 es de tipo float64
TxsPAT_T04 es de tipo float64
FacCCPC_T04 es de tipo float64
TxsCCPC_T04 es de tipo float64
FacCCOT_T04 es de tipo float64
TxsCCOT_T04 es de tipo float64
FacCOL_T04 es de tipo float64
TxsCOL_T04 es de tipo float64
FacDebCom_T04 es de tipo float64
TxsDebCom_T04 es de tipo float64
FacDebAtm_T04 es de tipo float64
TxsDebAtm_T04 es de tipo float64
Col_T04 es de tipo float64
ColL1T0_T04 es de tipo float64
ColL1TE_T04 es de tipo float64
ColL2T0_T04 es de tipo float64
ColL2AC_T04 es de tipo float64
ColL2CC_T04 es de tipo float64
ColMx_T04 es de tipo float64
PagoNac_T04 es de tipo float64
PagoInt_T04 es de tipo float64
EeccNac_T04 es de tipo float64
EeccInt_T04 es de tipo float64
UsoL1_T04 es de tipo float64
UsoL2_T04 es de tipo float64
UsoLI_T04 es de tipo float64
IndRev_T04 es de tipo object
FlgAct_T03 es de tipo float64
FlgActCN_T03 es de tipo float64
FlgActCI_T03 es de tipo float64
FlgActAN_T03 es de tipo float64
FlgActAI_T03 es de tipo float64
FlgActPAT_T03 es de tipo float64
FlgActCCPC_T03 es de tipo float64
FlgActCCOT_T03 es de tipo float64
FlgActCOL_T03 es de tipo float64
Fac_T03 es de tipo float64
Txs_T03 es de tipo float64
FacCN_T03 es de tipo float64
TxsCN_T03 es de tipo float64
FacCI_T03 es de tipo float64
TxsCI_T03 es de tipo float64
FacAN_T03 es de tipo float64
TxsAN_T03 es de tipo float64
FacAI_T03 es de tipo float64
TxsAI_T03 es de tipo float64
FacPAT_T03 es de tipo float64
TxsPAT_T03 es de tipo float64
FacCCPC_T03 es de tipo float64
TxsCCPC_T03 es de tipo float64
FacCCOT_T03 es de tipo float64
TxsCCOT_T03 es de tipo float64
FacCOL_T03 es de tipo float64
TxsCOL_T03 es de tipo float64
FacDebCom_T03 es de tipo float64
TxsDebCom_T03 es de tipo float64
FacDebAtm_T03 es de tipo float64
TxsDebAtm_T03 es de tipo float64
Col_T03 es de tipo float64
ColL1T0_T03 es de tipo float64
ColL1TE_T03 es de tipo float64
ColL2T0_T03 es de tipo float64
ColL2AC_T03 es de tipo float64
ColL2CC_T03 es de tipo float64
ColMx_T03 es de tipo float64
PagoNac_T03 es de tipo float64
PagoInt_T03 es de tipo float64
EeccNac_T03 es de tipo float64
EeccInt_T03 es de tipo float64
UsoL1_T03 es de tipo float64
UsoL2_T03 es de tipo float64
UsoLI_T03 es de tipo float64
IndRev_T03 es de tipo object
FlgAct_T02 es de tipo float64
FlgActCN_T02 es de tipo float64
FlgActCI_T02 es de tipo float64
FlgActAN_T02 es de tipo float64
FlgActAI_T02 es de tipo float64
FlgActPAT_T02 es de tipo float64
FlgActCCPC_T02 es de tipo float64
FlgActCCOT_T02 es de tipo float64
FlgActCOL_T02 es de tipo float64
Fac_T02 es de tipo float64
Txs_T02 es de tipo float64
FacCN_T02 es de tipo float64
TxsCN_T02 es de tipo float64
FacCI_T02 es de tipo float64
TxsCI_T02 es de tipo float64
FacAN_T02 es de tipo float64
TxsAN_T02 es de tipo float64
FacAI_T02 es de tipo float64
TxsAI_T02 es de tipo float64
FacPAT_T02 es de tipo float64
TxsPAT_T02 es de tipo float64
FacCCPC_T02 es de tipo float64
TxsCCPC_T02 es de tipo float64
FacCCOT_T02 es de tipo float64
TxsCCOT_T02 es de tipo float64
FacCOL_T02 es de tipo float64
TxsCOL_T02 es de tipo float64
FacDebCom_T02 es de tipo float64
TxsDebCom_T02 es de tipo float64
FacDebAtm_T02 es de tipo float64
TxsDebAtm_T02 es de tipo float64
Col_T02 es de tipo float64
ColL1T0_T02 es de tipo float64
ColL1TE_T02 es de tipo float64
ColL2T0_T02 es de tipo float64
ColL2AC_T02 es de tipo float64
ColL2CC_T02 es de tipo float64
ColMx_T02 es de tipo float64
PagoNac_T02 es de tipo float64
PagoInt_T02 es de tipo float64
EeccNac_T02 es de tipo float64
EeccInt_T02 es de tipo float64
UsoL1_T02 es de tipo float64
UsoL2_T02 es de tipo float64
UsoLI_T02 es de tipo float64
IndRev_T02 es de tipo object
FlgAct_T01 es de tipo int64
FlgActCN_T01 es de tipo int64
FlgActCI_T01 es de tipo int64
FlgActAN_T01 es de tipo int64
FlgActAI_T01 es de tipo int64
FlgActPAT_T01 es de tipo int64
FlgActCCPC_T01 es de tipo int64
FlgActCCOT_T01 es de tipo int64
FlgActCOL_T01 es de tipo int64
Fac_T01 es de tipo int64
Txs_T01 es de tipo int64
FacCN_T01 es de tipo int64
TxsCN_T01 es de tipo int64
FacCI_T01 es de tipo int64
TxsCI_T01 es de tipo int64
FacAN_T01 es de tipo int64
TxsAN_T01 es de tipo int64
FacAI_T01 es de tipo int64
TxsAI_T01 es de tipo int64
FacPAT_T01 es de tipo int64
TxsPAT_T01 es de tipo int64
FacCCPC_T01 es de tipo int64
TxsCCPC_T01 es de tipo int64
FacCCOT_T01 es de tipo int64
TxsCCOT_T01 es de tipo int64
FacCOL_T01 es de tipo int64
TxsCOL_T01 es de tipo int64
FacDebCom_T01 es de tipo int64
TxsDebCom_T01 es de tipo int64
FacDebAtm_T01 es de tipo int64
TxsDebAtm_T01 es de tipo int64
Col_T01 es de tipo float64
ColL1T0_T01 es de tipo int64
ColL1TE_T01 es de tipo float64
ColL2T0_T01 es de tipo int64
ColL2AC_T01 es de tipo int64
ColL2CC_T01 es de tipo int64
ColMx_T01 es de tipo float64
PagoNac_T01 es de tipo int64
PagoInt_T01 es de tipo float64
EeccNac_T01 es de tipo float64
EeccInt_T01 es de tipo float64
UsoL1_T01 es de tipo float64
UsoL2_T01 es de tipo int64
UsoLI_T01 es de tipo float64
IndRev_T01 es de tipo object
target es de tipo int64
Unnamed: 574 es de tipo float64

In [41]:
num_rows = df.shape[0]
print(f'El dataset tiene {num_rows} Filas.')

El dataset tiene 51124 Filas.

# Hipótesis

* nigga
* andru
* Machuquin

## **Fase 2: Data Understanding**

### Validación de datos nulos

In [48]:
df.isnull().sum()

Id                  0
Subsegmento         0
Sexo                1
Region             53
Edad                0
                ...
UsoL2_T01           0
UsoLI_T01           0
IndRev_T01          0
target              0
Unnamed: 574    51124
Length: 575, dtype: int64

In [50]:
df.nunique()

Id              51124
Subsegmento        16
Sexo                2
Region             13
Edad               79
                ...
UsoL2_T01       29760
UsoLI_T01        2376
IndRev_T01          3
target              2
Unnamed: 574        0
Length: 575, dtype: int64

### **Medidas de posición**

In [62]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Id,51124.0,25562.500000,14758.371918,1.00,12781.75,25562.5,38343.25,51124.00
Subsegmento,51124.0,182.024274,29.276596,151.00,160.00,170.0,210.00,959.00
Region,51071.0,10.828220,3.392703,1.00,9.00,13.0,13.00,13.00
Edad,51124.0,38.702879,13.302573,9.00,28.00,35.0,46.00,104.00
Renta,37759.0,663077.078726,409279.460268,1.00,419999.00,567012.0,814903.50,13089327.00
...,...,...,...,...,...,...,...,...
UsoL1_T01,51124.0,184092.343547,289173.134339,-3763996.60,17707.50,81129.0,227814.50,6911556.00
UsoL2_T01,51124.0,136032.715750,432538.882162,-4.00,0.00,29646.5,102102.25,11785487.00
UsoLI_T01,51124.0,8.294372,113.215624,-7785.12,0.00,0.0,0.00,3929.81
target,51124.0,0.089977,0.286152,0.00,0.00,0.0,0.00,1.00
Unnamed: 574,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Gráficos

## **Fase 3: Data Preparation**